services:
  catalog-service:
    image: 'catalog-service'
    container_name: 'catalog-service'
    networks:
      - 'backend'
    ports:
      - '9001:9001'
      - '8001:8001'
    depends_on:
      - 'pg'
    environment:
      - 'BPL_JVM_THREAD_COUNT=50'
      - 'BPL_DEBUG_ENABLED=true'
      - 'BPL_DEBUG_PORT=8001'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://pg:5432/bookshopdb'
      - 'SPRING_PROFILES_ACTIVE=testdata'
  pg:
    image: 'postgres'
    container_name: 'pg'
    volumes:
      - './data/pg:/var/lib/postgresql/data'
    networks:
      - 'backend'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=master'
      - 'POSTGRES_PASSWORD=master1234'
      - 'POSTGRES_DB=bookshopdb'
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    restart: 'always'
    volumes:
      - './data/pgadmin:/var/lib/pgadmin'
    networks:
      - 'backend'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=master@pgadmin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=master1234'
    ports:
      - '8080:80'
    depends_on:
      - 'pg'

networks:
  backend:
    driver: 'bridge'

  # vault:
  #   image: "hashicop/vault"
  #   container_name: "valut"
  #   volumes:
  #     - "./docker/vault/config:/valut/config"
  #     - "./docker/vault/file:/valut/file"
  #     - "./docker/vault/logs:/vault/logs"
  #   ports:
  #     - "8200:8200"

 