CREATE SEQUENCE IF NOT EXISTS books_seq
  START WITH 1 
  INCREMENT BY 1 
  MINVALUE 1 
  MAXVALUE 9223372036854775807 
  CACHE 50;

CREATE TABLE IF NOT EXISTS books (
  id      BIGINT DEFAULT NEXTVAL('books_seq') PRIMARY KEY,
  isbn    TEXT UNIQUE NOT NULL,
  title   TEXT NOT NULL,
  author  TEXT NOT NULL,
  price   FLOAT8 NOT NULL,
  version BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);