name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: microsoft
          java-version: 17
          cache: gradle
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3.6.4
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          output-format: sarif
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with: 
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and outputs.sarif
        run: |
          chmod +x gradlew
          ./gradlew build
